export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="${ZSH_CUSTOM:-$ZSH/custom}"
export EDITOR="nvim"
export N_PREFIX="$HOME/.n"
export PATH="$HOME/.local/bin:$N_PREFIX/bin:$PATH"

ZSH_THEME="robbyrussell"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source "$ZSH/oh-my-zsh.sh"

if [ -f /usr/share/doc/fzf/examples/key-bindings.zsh ]; then
  source /usr/share/doc/fzf/examples/key-bindings.zsh
fi

if [ -f /usr/share/doc/fzf/examples/completion.zsh ]; then
  source /usr/share/doc/fzf/examples/completion.zsh
fi

alias ll="ls -lah"
alias gs="git status"
alias gc="git commit"
alias gp="git push"
alias gl="git pull"
alias fd="fdfind"
alias pn="pnpm"

HISTSIZE=10000
SAVEHIST=10000

setopt autocd
